apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: management
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`headlamp.ygg.dedyn.io`)
      kind: Rule
      services:
        - name: headlamp
          kind: Service
          port: 80
