apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cluster-issuer
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`headlamp.ygg.dedyn.io`)
      kind: Rule
      services:
        - name: headlamp
          kind: Service
          port: 80

  tls:
    domains:
      - main: headlamp.ygg.dedyn.io
    secretName: headlamp-tls-secret
