apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shellspell
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/msadley/shellspell.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shellspell
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: shellspell
  path: "./k8s"
  prune: true
  timeout: 5m
