apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shellspell
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/shellspell
  prune: true
  targetNamespace: shellspell
  sourceRef:
    kind: GitRepository
    name: flux-system
