apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: syncthing
  name: syncthing
spec:
  ports:
    - name: "22000"
      port: 22000
      targetPort: 22000
    - name: 22000-udp
      port: 22000
      protocol: UDP
      targetPort: 22000
    - name: "21027"
      port: 21027
      protocol: UDP
      targetPort: 21027
    - name: web
      port: 80
      targetPort: 8384
  selector:
    io.kompose.service: syncthing
