apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: yggdrasil
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/msadley/yggdrasil
  ref:
    branch: master
