apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: syncthing
  name: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
