ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: "traefik"
    hosts:
      - host: syncthing.ygg.dedyn.io
        paths:
          - path: /
            pathType: Prefix

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    mountPath: /var/syncthing
    size: 5Gi
