apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  interval: 10m
  chart:
    spec:
      chart: syncthing
      version: "5.1.2"
      sourceRef:
        kind: HelmRepository
        name: johanneskastl
        namespace: syncthing
      interval: 10m

  values:
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod-cluster-issuer
        hosts:
          - host: syncthing.ygg.dedyn.io
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - syncthing.ygg.dedyn.io
            secretName: syncthing-tls-secret

    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        mountPath: /var/syncthing
        size: 5Gi
