apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: plane
spec:
  instances: 3

  postgresql:
    synchronous:
      method: any
      number: 1

  storage:
    size: 5Gi
