apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plane
  namespace: plane
spec:
  interval: 10m
  chart:
    spec:
      chart: plane-ce
      version: "1.8.4"
      sourceRef:
        kind: HelmRepository
        name: plane
        namespace: plane
      interval: 10m

  values:
    planeVersion: v1.4.2

    ingress:
      enabled: true
      ingressClass: traefik
      appHost: plane.ygg.dedyn.io

    postgres:
      local_setup: false

    env:
      # TODO: remove this ugly thing and inject it correctly
      pgdb_remote_url: postgresql://app:pPL7IoZWQVxI0jgfgsO8W3MSvFA4H6jFFdD3DJDxU4unAJfvrFtKI9xvLe6cjUIA@postgres-cluster-rw.plane:5432/app
      secret_key: amoguspotatus007
